SELECT * FROM currency.CURRENCIES;
SELECT * FROM currency.CURRENCIES WHERE abbr = 'EUR';
SELECT COUNT(*) FROM currency.CURRENCIES;
SELECT * FROM currency.CURRENCIES WHERE exr = (SELECT MAX(exr) FROM currency.CURRENCIES);
